# Generated by Django 4.2.2 on 2023-06-22 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField(max_length=255)),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(
                            2023, 6, 22, 12, 38, 36, 4705, tzinfo=datetime.timezone.utc
                        ),
                    ),
                ),
            ],
        ),
    ]
