# Generated by Django 4.2.2 on 2023-07-09 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
