# Generated by Django 4.2.2 on 2023-06-23 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 23, 5, 44, 35, 35580, tzinfo=datetime.timezone.utc)),
        ),
    ]
